- name: demo on conditions
  hosts: localhost
  tasks:
    - name: learn devops
      ansible.builtin.debug:
        msg: start learning devops
      when: subject == " devops "

    - name: learn aws
      ansible.builtin.debug:
          msg: start learning aws
      when: subject == " aws "