- name: loops
  hosts: localhost
  tasks:
    - name: Loop Demo
      ansible.builtin.debug:
        msg: Learn, {{ item }}
      loop:
        - unix
        - ansible
        - terraform

    - name: Loop Demo on maps and using conditions
      ansible.builtin.debug:
        msg: Learn, {{ item.name }} , cost of learning is {{ item.cost }}
      loop:
        - { name: "unix" , cost: 100 , run: true }
        - { name: "ansible" , cost: 200 , run: true}
        - { name: "terraform" , cost: 300 , run: false}
      when: item.run