- name: loops
  hosts: localhost
  tasks:
    - name: Loop Demo
      ansible.builtin.debug:
        msg: Learn, {{ item }}
      loop:
        - unix
        - ansible
        - terraform

    - name: Loop Demo on maps
      ansible.builtin.debug:
        msg: Learn, {{ item.name }} , cost of learning is {{ item.cost }}
      loop:
        - { name: "unix" , cost: 100 }
        - { name: "ansible" , cost: 200 }
        - { name: "terraform" , cost: 300 }