- name: Demo on handlers
  hosts: localhost
  tasks:
    - name: Copy Sample
      ansible.builtin.template:
        src: sample.txt
        dest: /tmp/sample.txt
      notify: Say hello again

handlers:
  - name: Say hello again
    ansible.builtin.debug:
      msg: hello {{ name }} again!!
